name: Build

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - uses: bahmutov/npm-install@v1

      - name: test
        run: npm run test

      - name: build
        run: |
          mkdir -p Installers
          rm -rf Installers/*
          npm run pkg-win
          mv tpgfe.exe base/Win/TPGeForceExperience/
          cd base/Win
          7z a -tzip ../../Installers/TPGeForceExperience-Win.tpp TPGeForceExperience
          cd ../../

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Installers/*.tpp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
